import crypto from 'node:crypto';
import {createRequest,clean,httpUrl,encodeEpisode,decodeEpisode,UA} from './lib/cat.js';
export function __jsEvalReturn(){
 const request=createRequest();let host,secret;
 async function init(cfg){host=httpUrl(cfg.ext.host).replace(/\/$/,'');secret=cfg.ext.signKey;if(!secret)throw Error('AppRJ 缺少公开协议签名参数');}
 function signature(){const timestamp=String(Math.floor(Date.now()/1000));return {timestamp,sign:crypto.createHash('md5').update(secret+timestamp).digest('hex')};}
 async function api(path,fields={}){const form=new FormData();for(const[k,v]of Object.entries({...fields,...signature()}))form.set(k,String(v));const response=await request(host+path,{method:'POST',headers:{'user-agent':'okhttp-okgo/jeasonlzy'},body:form});const root=JSON.parse(response.content);if(root.code!==1||!root.data)throw Error('AppRJ 接口未返回有效数据');return root.data;}
 function videos(rows=[]){return rows.map(v=>({vod_id:String(v.vod_id),vod_name:clean(v.vod_name),vod_pic:v.vod_pic_thumb||v.vod_pic||'',vod_remarks:v.vod_remarks||''}));}
 async function home(){const data=await api('/v3/type/top_type');const classes=(data.list||[]).map(x=>({type_id:String(x.type_id),type_name:x.type_name}));if(!classes.length)throw Error('AppRJ 没有分类');const filters={};for(const c of data.list){filters[c.type_id]=['extend','area','year','lang'].filter(k=>Array.isArray(c[k])&&c[k].length>1).map(k=>({key:k==='extend'?'class':k,name:{extend:'类型',area:'地区',year:'年份',lang:'语言'}[k],value:c[k].map(v=>({n:v,v:v==='全部'?'':v}))}));}const rows=JSON.parse(await category(classes[0].type_id));return JSON.stringify({class:classes,filters,list:rows.list});}
 async function category(id,page=1,filter=false,extend={}){page=Math.max(1,Number(page)||1);const fields={type_id:id,page,limit:12};for(const k of ['class','area','year','lang'])if(extend[k])fields[k]=extend[k];const data=await api('/v3/home/type_search',fields);return JSON.stringify({page,pagecount:(data.list||[]).length? page+1:page,list:videos(data.list)});}
 async function search(wd,quick=false,page=1){const data=await api('/v3/home/search',{keyword:wd,page,limit:12});return JSON.stringify({page:Number(page),list:videos(data.list)});}
 async function detail(id){const v=await api('/v3/home/vod_details',{vod_id:id}),names=[],groups=[];for(const line of v.vod_play_list||[]){const episodes=(line.urls||[]).map(e=>clean(e.name)+'$'+encodeEpisode({url:e.url,parsers:line.parse_urls||[],ua:line.ua||UA,referer:line.referer||''}));if(!episodes.length)continue;names.push(clean(line.name||line.title||line.flag||'线路'));groups.push(episodes.join('#'));}if(!groups.length)throw Error('AppRJ 详情没有集数');return JSON.stringify({list:[{...videos([v])[0],vod_content:v.vod_content||'',vod_actor:v.vod_actor||'',vod_director:v.vod_director||'',vod_play_from:names.join('$$$'),vod_play_url:groups.join('$$$')}]});}
 async function play(flag,id){const e=decodeEpisode(id);let media,ua=e.ua||UA;const errors=[];if(e.parsers.length){for(const p of e.parsers.slice(0,3)){try{const endpoint=new URL(httpUrl(p+encodeURIComponent(e.url)));for(const[k,v]of Object.entries(signature()))endpoint.searchParams.set(k,v);const response=await request(endpoint.href);const root=JSON.parse(response.content);media=root.url||root.data?.url;ua=root.UA||ua;if(media)break;}catch(error){errors.push(error.message);}}}else if(/^https?:/.test(e.url))media=e.url;if(!media)throw Error('AppRJ 播放解析失败'+(errors.length?'：'+errors[0]:''));return JSON.stringify({parse:0,url:httpUrl(media),header:{'User-Agent':ua,...(e.referer?{Referer:e.referer}:{})}});}
 return {init,home,category,search,detail,play};
}
