import {createRequest,load,httpUrl,clean,encodeEpisode,decodeEpisode,UA} from './lib/cat.js';
const families=['Movie','Tv','Zy','Dm','qita'];
export function __jsEvalReturn(){
 const request=createRequest();let host,searchUrl,searchField;
 async function init(cfg){host=new URL(httpUrl(cfg.ext.host)).origin;}
 async function page(path){const target=httpUrl(path,host);if(new URL(target).origin!==host)throw Error('奥特页面标识无效');const response=await request(target);return {$:load(response.content),html:response.content,url:response.url};}
 function list($){const rows=new Map();$('a[href]').each((_,el)=>{const a=$(el),path=a.attr('href');if(!/^\/(Movie|Tv|Zy|Dm|qita)\/[^?#]+\/$/.test(path)||rows.has(path))return;const img=a.find('img').first();if(!img.length)return;const name=img.attr('alt')||a.attr('title')||a.text();if(!name?.trim())return;const pic=img.attr('data-original')||img.attr('data-src')||img.attr('src')||'';rows.set(path,{vod_id:path,vod_name:clean(name),vod_pic:pic?httpUrl(pic,host):'',vod_remarks:a.find('.badge,.pic-text').first().text().trim()});});return [...rows.values()];}
 async function home(){const {$}=await page('/');const classes=[];$('.mr-auto a[href]').each((_,el)=>{const a=$(el),id=a.attr('href').match(/^\/(Movie|Tv|Zy|Dm|qita)\/index\.html$/)?.[1];if(id)classes.push({type_id:id,type_name:a.text().trim()});});if(!classes.length)throw Error('奥特网站导航结构已更新');return JSON.stringify({class:classes,list:list($)});}
 async function category(id,pg=1){if(!families.includes(id))throw Error('无效奥特分类');pg=Math.max(1,Number(pg)||1);const {$}=await page('/'+id+'/index'+(pg===1?'':pg)+'.html');return JSON.stringify({page:pg,pagecount:$('a').toArray().some(e=>/下一|»/.test($(e).text()))?pg+1:pg,list:list($)});}
 async function search(wd,quick=false,pg=1){if(!searchUrl){const {$}=await page('/');const form=$('form[action]').toArray().find(e=>$(e).find('input[name="searchword"],input[name="wd"]').length);if(!form)throw Error('奥特搜索表单已更新');searchUrl=new URL($(form).attr('action'),host);if(searchUrl.origin!==host)throw Error('奥特搜索地址异常');searchField=$(form).find('input[name="searchword"],input[name="wd"]').first().attr('name');}const target=new URL(searchUrl);target.searchParams.set(searchField,wd);target.searchParams.set('page',String(Math.max(1,Number(pg)||1)));const {$}=await page(target.href);if($('input[name*="validate"],input[name*="checkcode"],img[src*="captcha"]').length||/验证码|加法验证/.test($('title').text()))throw Error('奥特搜索需要源站验证');return JSON.stringify({page:Number(pg),list:list($)});}
 async function detail(id){if(!/^\/(Movie|Tv|Zy|Dm|qita)\/[^?#]+\/$/.test(id))throw Error('无效奥特影片标识');const {$}=await page(id),names=[],groups=[];$('[id="player_list"]').each((i,el)=>{const block=$(el),episodes=[];block.find('a[href*="/play-"]').each((_,link)=>{const a=$(link);episodes.push(clean(a.text())+'$'+encodeEpisode({path:a.attr('href')}));});if(episodes.length){names.push(clean(block.find('.card-header b').text()||'线路'+(i+1)));groups.push(episodes.join('#'));}});if(!groups.length)throw Error('奥特详情没有集数');const img=$('img').toArray().find(e=>/upload/.test($(e).attr('src')||''));return JSON.stringify({list:[{vod_id:id,vod_name:$('#video').attr('data-pname')||$('h1').first().text()||$('title').text(),vod_pic:img?httpUrl($(img).attr('src'),host):'',vod_play_from:names.join('$$$'),vod_play_url:groups.join('$$$')}]});}
 async function play(flag,id){const {path}=decodeEpisode(id);if(!/^\/(Movie|Tv|Zy|Dm|qita)\/[^?#]+\/play-\d+-\d+\.html$/.test(path))throw Error('无效奥特集数');const {html,url}=await page(path),encoded=html.match(/\bvar\s+now\s*=\s*base64decode\(["']([A-Za-z0-9+/=]*)["']\)/)?.[1];if(!encoded)throw Error('奥特播放器格式已更新');const media=httpUrl(Buffer.from(encoded,'base64').toString('utf8'));if(!/\.(m3u8|mp4)(?:[?#]|$)/i.test(media))throw Error('该奥特线路需要额外解析，尚未适配');return JSON.stringify({parse:0,url:media,header:{'User-Agent':UA,Referer:url}});}
 return {init,home,category,search,detail,play};
}
