import {createRequest,load,UA,httpUrl,clean,encodeEpisode,decodeEpisode} from './lib/cat.js';
import {createDecipheriv} from 'node:crypto';
// Some upstream players publish a base64 AES payload with a per-page IV.
export function decodePlayerPayload(html){
 const payload=html.match(/\bvar\s+player\s*=\s*["']([^"']+)["']/)?.[1];
 const iv=html.match(/\bvar\s+rand\s*=\s*["']([^"']+)["']/)?.[1];
 if(!payload||!iv)return '';
 if(Buffer.byteLength(iv)!==16)throw new Error('厂长播放器 IV 长度无效');
 try{const decipher=createDecipheriv('aes-128-cbc',Buffer.from('VFBTzdujpR9FWBhe'),Buffer.from(iv));const decoded=Buffer.concat([decipher.update(Buffer.from(payload,'base64')),decipher.final()]).toString('utf8');return httpUrl(JSON.parse(decoded).url);}catch{throw new Error('厂长播放器数据解密失败');}
}
export function __jsEvalReturn(){
 const request=createRequest();let urls=[],host='',resolvedAt=0,searchPath='/?s=';const categoryPaths=new Map();
 async function init(cfg){const ext=cfg.ext||{};urls=typeof ext==='string'?[ext]:ext.siteUrls||[];if(!urls.length)throw new Error('请配置厂长入口地址');}
 async function resolve(){if(host&&Date.now()-resolvedAt<15*60000)return host;for(const entry of urls)try{const response=await request(httpUrl(entry));if(/\/movie\/|\/movie_bt/.test(response.content)){host=new URL(response.url).origin;const $=load(response.content),form=$('form.w-search-form'),field=form.find('input[type="text"]').attr('name');if(form.attr('action')&&field){const action=new URL(form.attr('action'),host);if(action.origin===host)searchPath=action.pathname+'?'+encodeURIComponent(field)+'=';}resolvedAt=Date.now();return host;}}catch{}throw new Error('厂长入口不可用或已改变页面结构');}
 async function page(value){const origin=await resolve();const target=httpUrl(value,origin);if(new URL(target).origin!==origin)throw new Error('厂长页面标识不属于本站');const response=await request(target,{headers:{referer:origin+'/'}});const $=load(response.content);if(/验证码|captcha/i.test($('title').text())&&!$('a[href*="/movie/"]').length)throw new Error('源站要求搜索验证，暂时无法自动搜索');return {$,html:response.content,url:response.url};}
 function list($){const records=new Map();$('a[href*="/movie/"]').each((_,element)=>{const link=$(element),href=link.attr('href')||'',id=href.match(/\/movie\/([^/?]+)\.html/)?.[1];if(!id||records.has(id))return;const image=link.find('img').first();const title=link.attr('title')||image.attr('alt')||link.closest('li').find('h3').text().trim();if(!title)return;const pic=image.attr('data-original')||image.attr('data-src')||image.attr('src')||'';records.set(id,{vod_id:id,vod_name:clean(title),vod_pic:pic?httpUrl(pic,host):'',vod_remarks:link.closest('li').find('.jidi,.hdinfo').first().text().trim()});});return [...records.values()];}
 async function home(){const {$}=await page('/movie_bt/');const classes=new Map();$('[cat-url*="movie_bt_series"]').each((_,element)=>{const item=$(element),href=item.attr('cat-url');const tid=href?.match(/movie_bt_series\/([^/]+)/)?.[1];if(tid&&!/会员/.test(item.text())){classes.set(tid,{type_id:tid,type_name:item.text().trim()});categoryPaths.set(tid,new URL(href,host).pathname);}});if(!classes.size)throw new Error('厂长没有返回分类，页面结构可能已更新');return JSON.stringify({class:[...classes.values()],list:list($)});}
 async function homeVod(){const {$}=await page('/');return JSON.stringify({list:list($)});}
 async function category(tid,pg=1){if(!/^[\p{L}\p{N}_%-]+$/u.test(tid))throw new Error('无效分类');const pageNumber=Math.max(1,Number(pg)||1);const {$}=await page((categoryPaths.get(tid)||'/movie_bt_series/'+tid)+(pageNumber>1?'/page/'+pageNumber:''));const videos=list($);return JSON.stringify({page:pageNumber,pagecount:pageNumber+($('a.next,.pagenavi_txt a').toArray().some(e=>/下一|›|»|>/.test($(e).text()))?1:0),limit:videos.length,total:videos.length,list:videos});}
 async function search(wd,quick=false,pg=1){await resolve();const {$}=await page(searchPath+encodeURIComponent(wd)+(Number(pg)>1?'&paged='+Number(pg):''));return JSON.stringify({list:list($),page:Number(pg)});}
 async function detail(id){if(!/^\d+$/.test(id))throw new Error('无效视频标识');const {$}=await page('/movie/'+id+'.html');const episodes=$('.paly_list_btn a[href*="/v_play/"]').toArray().map((element,index)=>{const item=$(element);return clean(item.text()||String(index+1))+'$'+encodeEpisode({path:new URL(item.attr('href'),host).pathname});});if(!episodes.length)throw new Error('厂长详情没有集数');return JSON.stringify({list:[{vod_id:id,vod_name:$('.moviedteail_tt h1').text().trim(),vod_pic:$('.dyimg img').attr('src')||'',vod_content:$('.yp_context').text().trim(),vod_play_from:'厂长',vod_play_url:episodes.join('#')}]});}
 function reverseCloud(text){const code=text.match(/var\s+url\s*=\s*['"]([^'"]+)['"]/)?.[1];if(!code)return '';const reversed=[...code].reverse().join('');if(!/^[a-f\d]+$/i.test(reversed))return '';const decoded=Buffer.from(reversed,'hex').toString(),middle=(decoded.length-7)/2;if(!Number.isInteger(middle))return '';return decoded.slice(0,middle)+decoded.slice(middle+7);}
 function direct(text){return text.match(/(?:\b(?:url|file)\s*[:=]|<(?:video|source)\b[^>]*\bsrc=)\s*['"](https?:[^'"\s]+\.(?:m3u8|mp4)[^'"\s]*)['"]/)?.[1]?.replaceAll('\\/','/')||'';}
 async function play(flag,id){const episode=decodeEpisode(id);if(!/^\/v_play\/[^/]+\.html$/.test(episode.path))throw new Error('无效播放页面');const {$,html,url:referer}=await page(episode.path);let media=direct(html);if(!media){const iframe=$('iframe[src]').toArray().find(e=>/Cloud|player|play|video/i.test($(e).attr('src')));if(iframe){const nestedUrl=new URL(httpUrl($(iframe).attr('src'),host));const parameter=nestedUrl.searchParams.get('url');if(parameter&&/^https?:.*\.(m3u8|mp4)(?:\?|$)/i.test(parameter))media=parameter;else{const nested=await request(nestedUrl.href,{headers:{referer}});media=direct(nested.content)||reverseCloud(nested.content)||decodePlayerPayload(nested.content);}}}
  if(!media)media=decodePlayerPayload(html);
  if(!media)throw new Error('厂长播放页使用尚未适配的加密格式');return JSON.stringify({parse:0,url:httpUrl(media),header:{'User-Agent':UA,Referer:referer}});
 }
 return {init,home,homeVod,category,search,detail,play};
}
