import {createRequest,load,httpUrl,clean,encodeEpisode,decodeEpisode,UA} from './lib/cat.js';
export function __jsEvalReturn(){
 const request=createRequest();let host;
 async function init(cfg){host=new URL(httpUrl(cfg.ext.host)).origin;}
 async function page(path){const url=httpUrl(path,host);if(new URL(url).origin!==host)throw Error('动漫巴士页面标识无效');const response=await request(url);return {$:load(response.content),html:response.content,url:response.url};}
 function list($){const rows=new Map();$('a[href^="/v/"]').each((_,el)=>{const a=$(el),id=a.attr('href')?.match(/^\/v\/(\d+)\.html$/)?.[1];if(!id||rows.has(id))return;const container=a.closest('li'),cover=container.find('.cover'),img=container.find('img');rows.set(id,{vod_id:id,vod_name:clean(container.find('a.title').text()||a.attr('title')||a.text()).replace(/在线观看$/,''),vod_pic:cover.attr('data-bg')||img.attr('data-src')||img.attr('src')||'',vod_remarks:container.find('.desc').text().trim()});});return [...rows.values()];}
 async function home(){const {$}=await page('/');const classes=new Map();$('a[href^="/list-"]').each((_,el)=>{const a=$(el),id=a.attr('href').match(/^\/list-(\d+)\.html$/)?.[1];if(id&&!classes.has(id))classes.set(id,{type_id:id,type_name:a.text().trim()});});return JSON.stringify({class:[...classes.values()],list:list($)});}
 async function category(tid,pg=1){if(!/^\d+$/.test(tid))throw Error('无效分类');pg=Math.max(1,Number(pg)||1);const {$}=await page(`/list-${tid}-${pg}.html`);const videos=list($);return JSON.stringify({list:videos,page:pg,pagecount:$('a').toArray().some(el=>/下一页/.test($(el).text()))?pg+1:pg});}
 async function search(wd,quick=false,pg=1){const {$}=await page('/s----------.html?wd='+encodeURIComponent(wd)+'&page='+Math.max(1,Number(pg)||1));return JSON.stringify({list:list($),page:Number(pg)});}
 async function detail(id){if(!/^\d+$/.test(id))throw Error('无效视频标识');const {$}=await page('/v/'+id+'.html');const names=$('.play_from li').toArray().map(el=>clean($(el).text()));const groups=$('.play_list').toArray().map(el=>$(el).find('a[href^="/p/"]').toArray().map(a=>clean($(a).text())+'$'+encodeEpisode({path:$(a).attr('href')})).join('#'));if(!groups.length)throw Error('动漫巴士详情未返回集数');return JSON.stringify({list:[{vod_id:id,vod_name:$('h1').first().text().trim(),vod_content:$('.desc').text().trim(),vod_play_from:groups.map((_,i)=>names[i]||'线路'+(i+1)).join('$$$'),vod_play_url:groups.join('$$$')}]});}
 async function play(flag,id){const {path}=decodeEpisode(id);if(!/^\/p\/\d+-\d+-\d+\.html$/.test(path))throw Error('无效集数标识');const {$,url}=await page(path);const src=$('iframe[src]').first().attr('src');if(!src)throw Error('动漫巴士未返回播放器');const iframe=httpUrl(src,url),response=await request(iframe,{headers:{referer:url}});const raw=response.content.match(/window\.__HHJX_BOOTSTRAP__\s*=\s*(\{[^\n]*?\});?\s*<\/script>/)?.[1];if(!raw)throw Error('动漫巴士播放器协议已更新');const boot=JSON.parse(raw);if(boot.error)throw Error('动漫巴士播放器参数错误');const endpoint=new URL('/api/parse',iframe).href;const parsed=await request(endpoint,{method:'POST',headers:{'content-type':'application/json',referer:iframe},body:JSON.stringify({url:boot.url,t:boot.t,key:boot.key,client_fallback:false,...(boot.act===99?{act:99}:{})})});const result=JSON.parse(parsed.content);if(result.code!==200||!result.url)throw Error('动漫巴士解析未返回视频地址');if(result.ext==='youku')throw Error('该线路需要浏览器解析，尚未适配');let media=httpUrl(result.url,iframe);if(result.ext==='hls_rewrite'){const rewrite=new URL('/getts',iframe);for(const [k,v]of Object.entries({url:media,t:boot.t,key:boot.ts_key}))rewrite.searchParams.set(k,String(v));media=rewrite.href;}return JSON.stringify({parse:0,url:media,header:{'User-Agent':UA,Referer:iframe}});}
 return {init,home,category,search,detail,play};
}
